// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ArticleChangeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void articleAdd() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'/add\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//div[3]/a/span")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@name=\'title\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//form/div[2]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//section"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//section[2]/div/button"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("(//button[@type=\'button\'])[9]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void articleCommentAdd() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//article/div[2]/div[3]/div/a"));
      assert(elements.size() > 0);
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//a/span[2]")).click();
    vars.put("win2981", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2981").toString());
    {
      List<WebElement> elements = driver.findElements(By.xpath("//form/ul"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//form/div/div/div/div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//form/div/div/div/div/p")).click();
    {
      WebElement element = driver.findElement(By.xpath("//form/div/div/div/div"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>wow</p>'}", element);
    }
    driver.findElement(By.xpath("//span/button/span")).click();
  }
  @Test
  public void articleSave() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//article/div[2]/div[3]/div/div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//article/div[2]/div[3]/div/div")).click();
    driver.findElement(By.xpath("//div[5]/div/div/div/div/div/div/div")).click();
    vars.put("name", driver.findElement(By.xpath("//h2/a")).getText());
    driver.findElement(By.xpath("//a[contains(text(),\'Сохраненное\')]")).click();
    assertThat(driver.findElement(By.xpath("//h2/a")).getText(), is("vars.get(\"name\").toString()"));
  }
  @Test
  public void followAuthor() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    driver.findElement(By.xpath("//header/div/div/a")).click();
    assertThat(driver.findElement(By.xpath("//div[2]/div/div/span/button")).getText(), is("ПОДПИСАТЬСЯ"));
    driver.findElement(By.xpath("//div[2]/div/div/span/button")).click();
    assertThat(driver.findElement(By.xpath("//div[2]/div/div/span/button")).getText(), is("ОТПИСАТЬСЯ"));
  }
  @Test
  public void followTags() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    driver.findElement(By.xpath("//input[@name=\'q\']")).click();
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    driver.findElement(By.xpath("//section[2]/div/div/span")).click();
    driver.findElement(By.xpath("(//input[@value=\'\'])[3]")).sendKeys("Черный");
    driver.findElement(By.xpath("//div/div/div/div/div/div[2]/div/div[2]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//span[contains(.,\'Черный юмор\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//section[2]/div/div[2]/div/span"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//span[3]/span")).click();
    driver.findElement(By.xpath("//div[7]/div/div/div/div/div/div")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//header/div[3]/div/div")));
    }
    assertThat(driver.findElement(By.xpath("//header/div[3]/div/div")).getText(), is("ВЫЙТИ"));
  }
  @Test
  public void vIewSavedArticles() {
    driver.get("https://pikabu.ru/");
    driver.manage().window().setSize(new Dimension(1440, 960));
    js.executeScript("window.scrollTo(0,120)");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(text(),\'Сохраненное\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//a[contains(text(),\'Сохраненное\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//article/div[2]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//article[2]/div[2]"));
      assert(elements.size() > 0);
    }
  }
}
