// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginFormTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
/*    @Test
    public void loginSuccess() {
        driver.get("https://pikabu.ru/");
        driver.manage().window().setSize(new Dimension(1200, 952));
        driver.findElement(By.xpath("//input[@name=\'username\']")).click();
        driver.findElement(By.xpath("//input[@name=\'username\']")).sendKeys("happy_chicken");
        driver.findElement(By.xpath("//input[@name=\'password\']")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("lab3_tpo_pass");
        driver.findElement(By.xpath("(//button[@type=\'submit\'])[2]")).click();
        assertThat(driver.findElement(By.xpath("//div[2]/div/a")).getText(), is("brm82"));
    }
    @Test
    public void loginFails() {
        driver.get("https://pikabu.ru/");
        driver.manage().window().setSize(new Dimension(1200, 952));
        driver.findElement(By.xpath("//input[@name=\'username\']")).click();
        driver.findElement(By.xpath("//input[@name=\'username\']")).sendKeys("not_existing_login_tpo3");
        driver.findElement(By.xpath("//input[@name=\'password\']")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("any_password");
        driver.findElement(By.xpath("(//button[@type=\'submit\'])[2]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//form[@id=\'signin-form\']/div[4]"));
            assert(elements.size() > 0);
        }
        assertThat(driver.findElement(By.xpath("//form[@id=\'signin-form\']/div[4]")).getText(), is("Ошибка. Вы ввели неверные данные авторизации"));
    }*/
    @Test
    public void loginMinLength() {
        driver.get("https://pikabu.ru/");
        driver.manage().window().setSize(new Dimension(1200, 952));
        driver.findElement(By.xpath("//input[@name=\'username\']")).click();
        driver.findElement(By.xpath("//input[@name=\'username\']")).sendKeys("12");
        driver.findElement(By.xpath("//input[@name=\'password\']")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("11111");
        driver.findElement(By.xpath("(//button[@type=\'submit\'])[2]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[5]/div/div/div/div/div"));
            assert(elements.size() > 0);
        }
        assertThat(driver.findElement(By.xpath("//div[5]/div/div/div/div/div")).getText(), is("Минимальная длина 3 символа"));
    }
    @Test
    public void fbLoginFormAppears() {
        driver.get("https://pikabu.ru/");
        driver.manage().window().setSize(new Dimension(1200, 952));
        driver.findElement(By.xpath("//a[contains(@href, \'https://pikabu.ru/oauth.php?type=fb\')]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'login_link\']"));
            assert(elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'content\']/div/div"));
            assert(elements.size() > 0);
        }
        assertThat(driver.findElement(By.xpath("//div[@id=\'header_block\']/span/div")).getText(), is("Log in to Facebook"));
    }
    @Test
    public void vkLoginFormAppears() {
        driver.get("https://pikabu.ru/");
        driver.manage().window().setSize(new Dimension(1200, 952));
        driver.findElement(By.xpath("//a[contains(@href, \'https://pikabu.ru/oauth.php?type=vk\')]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//form[@id=\'login_submit\']/div"));
            assert(elements.size() > 0);
        }
        assertThat(driver.findElement(By.xpath("//div[@id=\'oauth_wrap_content\']/div[2]/div")).getText(), is("Log into VK to continue."));
    }
}
